---
title: "MSA Heatmap"
author: "Natalie Ogg A91030809"
format: pdf
---

```{r}
library(bio3d)
library(seqinr)
```

```{r}
alignment <- read.fasta("new_msa_alignment.clw.fst")

```

```{r}
seqidentity(alignment)

identity_matrix <- seqidentity(alignment)
```

```{r}
heatmap(identity_matrix, Rowv = NA, Colv = NA, scale = "none", main = "Sequence Identity Heatmap", cexRow = 0.8, cexCol = 0.8)
```
```{r}
con <- consensus(alignment)
```

```{r}
human_fasta <- ">NP_000530.1\nMNGTEGPNFYVPFSNATGVVRSPFEYPQYYLAEPWQFSMLAAYMFLLIVLGFPINFLTLYVTVQHKKLRTPLNYILLNLAVADLFMVLGGFTSTLYTSLHGYFVFGPTGCNLEGFFATLGGEIALWSLVVLAIERYVVVCKPMSNFRFGENHAIMGVAFTWVMALACAAPPLAGWSRYIPEGLQCSCGIDYYTLKPEVNNESFVIYMFVVHFTIPMIIIFFCYGQLVFTVKEAAAQQQESATTQKAEKEVTRMVIIMVIAFLICWVPYASVAFYIFTHQGSNFGPIFMTIPAFFAKSAAIYNPVIYIMMNKQFRNCMLTTICCGKNPLGDDEASATVSKTETSQVAPA"

human_seq <- read.fasta(text = human_fasta, seqonly = TRUE)
```

```{r}
library(seqinr)

human_fasta <- ">NP_000530.1\nMNGTEGPNFYVPFSNATGVVRSPFEYPQYYLAEPWQFSMLAAYMFLLIVLGFPINFLTLYVTVQHKKLRTPLNYILLNLAVADLFMVLGGFTSTLYTSLHGYFVFGPTGCNLEGFFATLGGEIALWSLVVLAIERYVVVCKPMSNFRFGENHAIMGVAFTWVMALACAAPPLAGWSRYIPEGLQCSCGIDYYTLKPEVNNESFVIYMFVVHFTIPMIIIFFCYGQLVFTVKEAAAQQQESATTQKAEKEVTRMVIIMVIAFLICWVPYASVAFYIFTHQGSNFGPIFMTIPAFFAKSAAIYNPVIYIMMNKQFRNCMLTTICCGKNPLGDDEASATVSKTETSQVAPA"

# Use char2vec to convert the sequence to a vector of characters
human_seq <- char2vec(human_fasta)

# Print the result
print(human_seq)

```


